# Generated by Django 6.0.7 on 2026-09-03 12:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0006_organizationinvitation_organizationmember'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='project',
            name='idx_projects_org_status',
        ),
        migrations.AddField(
            model_name='project',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['organization', 'is_archived', 'deleted_at'], name='idx_projects_org_archived'),
        ),
    ]
