# Generated by Django 6.0.7 on 2026-09-11 03:13

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_projectmember'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('category', models.CharField(choices=[('backlog', 'Backlog'), ('todo', 'To Do'), ('in_progress', 'In Progress'), ('done', 'Done')], max_length=20)),
                ('color', models.CharField(max_length=7)),
                ('icon', models.CharField(blank=True, max_length=50, null=True)),
                ('position', models.PositiveIntegerField()),
                ('is_default', models.BooleanField(default=False)),
                ('is_archived', models.BooleanField(default=False)),
                ('allow_from_backlog', models.BooleanField(default=True)),
                ('allow_incoming', models.BooleanField(default=True)),
                ('allow_outgoing', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_statuses', to='projects.project')),
            ],
            options={
                'db_table': 'workflow_statuses',
            },
        ),
        migrations.CreateModel(
            name='WorkflowTransition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=60)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('from_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_transitions', to='projects.workflowstatus')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_transitions', to='projects.project')),
                ('to_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_transitions', to='projects.workflowstatus')),
            ],
            options={
                'db_table': 'workflow_transitions',
            },
        ),
        migrations.AddIndex(
            model_name='workflowstatus',
            index=models.Index(fields=['project'], name='idx_workflow_status_project'),
        ),
        migrations.AddConstraint(
            model_name='workflowstatus',
            constraint=models.UniqueConstraint(fields=('project', 'name'), name='uq_status_name_per_project'),
        ),
        migrations.AddIndex(
            model_name='workflowtransition',
            index=models.Index(fields=['project'], name='idx_workflow_transition_project'),
        ),
        migrations.AddConstraint(
            model_name='workflowtransition',
            constraint=models.UniqueConstraint(fields=('project', 'from_status', 'to_status'), name='uq_workflow_transition'),
        ),
    ]
