# Generated by Django 6.0.7 on 2026-09-11 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_workflowstatus_workflowtransition_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='workflowtransition',
            new_name='idx_wf_transition_project',
            old_name='idx_workflow_transition_project',
        ),
    ]
