# Generated by Django 6.0.7 on 2026-09-24 07:54

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_sprint'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_number', models.PositiveIntegerField()),
                ('issue_type', models.CharField(choices=[('epic', 'Epic'), ('story', 'Story'), ('task', 'Task'), ('bug', 'Bug'), ('subtask', 'Sub-task')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('priority', models.CharField(choices=[('urgent', 'Urgent'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=20)),
                ('story_points', models.PositiveIntegerField(blank=True, null=True)),
                ('position', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_issues', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='projects.issue')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='projects.project')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reported_issues', to=settings.AUTH_USER_MODEL)),
                ('sprint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issues', to='projects.sprint')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issues', to='projects.workflowstatus')),
            ],
            options={
                'db_table': 'issues',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['project'], name='idx_issues_project'), models.Index(fields=['project', 'issue_type'], name='idx_issues_project_type'), models.Index(fields=['project', 'status'], name='idx_issues_project_status'), models.Index(fields=['project', 'sprint'], name='idx_issues_project_sprint'), models.Index(fields=['parent'], name='idx_issues_parent'), models.Index(fields=['assignee'], name='idx_issues_assignee')],
                'constraints': [models.UniqueConstraint(fields=('project', 'issue_number'), name='uq_issue_number_per_project')],
            },
        ),
    ]
