# Generated by Django 6.0.7 on 2026-09-25 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_issue'),
    ]

    operations = [
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('color', models.CharField(default='#999999', max_length=7)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labels', to='projects.project')),
            ],
            options={
                'db_table': 'labels',
            },
        ),
        migrations.CreateModel(
            name='IssueLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issue_labels', to='projects.issue')),
                ('label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issue_labels', to='projects.label')),
            ],
            options={
                'db_table': 'issue_labels',
            },
        ),
        migrations.AddIndex(
            model_name='label',
            index=models.Index(fields=['project'], name='idx_labels_project'),
        ),
        migrations.AddConstraint(
            model_name='label',
            constraint=models.UniqueConstraint(fields=('project', 'name'), name='uq_label_per_project'),
        ),
        migrations.AddIndex(
            model_name='issuelabel',
            index=models.Index(fields=['issue'], name='idx_issue_labels_issue'),
        ),
        migrations.AddIndex(
            model_name='issuelabel',
            index=models.Index(fields=['label'], name='idx_issue_labels_label'),
        ),
        migrations.AddConstraint(
            model_name='issuelabel',
            constraint=models.UniqueConstraint(fields=('issue', 'label'), name='uq_issue_label'),
        ),
    ]
