# Generated by Django 6.0.7 on 2026-09-26 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_label_issuelabel_label_idx_labels_project_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='labels',
            field=models.ManyToManyField(blank=True, related_name='issues', through='projects.IssueLabel', to='projects.label'),
        ),
    ]
