# Generated by Django 6.0.7 on 2026-09-28 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_comment_commentreaction_comment_idx_comments_issue_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='estimated_time',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
