# Generated by Django 6.0.7 on 2026-09-28 14:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_issue_due_date_issue_estimated_time'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='issue',
            index=models.Index(fields=['deleted_at'], name='idx_issues_deleted_at'),
        ),
    ]
