# Generated by Django 6.0.7 on 2026-09-29 10:11

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_issue_deleted_at_issue_idx_issues_deleted_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('object_key', models.CharField(max_length=500)),
                ('file_size', models.PositiveBigIntegerField()),
                ('mime_type', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='projects.issue')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_attachments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'attachments',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['issue'], name='idx_attachments_issue'), models.Index(fields=['uploaded_by'], name='idx_attachments_uploaded_by')],
                'constraints': [models.UniqueConstraint(fields=('issue', 'object_key'), name='uq_attachment_issue_object_key')],
            },
        ),
    ]
