# Generated by Django 6.0.7 on 2026-09-29 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='sprint',
            name='estimated_days',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
