# Generated by Django 6.0.7 on 2026-09-30 08:21

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_sprint_estimated_days'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_document_folders', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_folders', to='projects.project')),
            ],
            options={
                'db_table': 'document_folders',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['project'], name='idx_document_folders_project')],
                'constraints': [models.UniqueConstraint(fields=('project', 'name'), name='uq_document_folder_project_name')],
            },
        ),
    ]
