# Generated by Django 6.0.7 on 2026-10-05 05:35

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0016_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='IssueSprintHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moved_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sprint_history', to='projects.issue')),
                ('sprint', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issue_history', to='projects.sprint')),
            ],
            options={
                'db_table': 'issue_sprint_history',
                'ordering': ['moved_at'],
                'indexes': [models.Index(fields=['issue', 'moved_at'], name='idx_issue_sprint_history'), models.Index(fields=['sprint'], name='idx_sprint_issue_history')],
            },
        ),
    ]
