# Generated by Django 6.0.7 on 2026-10-05 06:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0017_issuesprinthistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuesprinthistory',
            name='sprint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='issue_sprint_history', to='projects.sprint'),
        ),
    ]
