# Generated by Django 6.0.7 on 2026-10-06 04:31

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0019_projecttag_document_tags_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='tags',
        ),
        migrations.CreateModel(
            name='DocumentTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_tags', to='projects.document')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_tags', to='projects.projecttag')),
            ],
            options={
                'db_table': 'document_tags',
                'indexes': [models.Index(fields=['document'], name='idx_document_tags_document'), models.Index(fields=['tag'], name='idx_document_tags_tag'), models.Index(fields=['created_at'], name='idx_document_tags_created_at')],
                'constraints': [models.UniqueConstraint(fields=('document', 'tag'), name='uq_document_tag')],
            },
        ),
    ]
