# Generated by Django 6.0.7 on 2026-10-06 11:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0020_remove_document_tags_documenttag'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='projects.document'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='issue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='projects.issue'),
        ),
        migrations.AddIndex(
            model_name='attachment',
            index=models.Index(fields=['document'], name='idx_attachments_document'),
        ),
        migrations.AddConstraint(
            model_name='attachment',
            constraint=models.CheckConstraint(condition=models.Q(('issue__isnull', False), ('document__isnull', False), _connector='OR'), name='attachment_has_parent'),
        ),
        migrations.AddConstraint(
            model_name='attachment',
            constraint=models.CheckConstraint(condition=models.Q(('issue__isnull', True), ('document__isnull', True), _connector='OR'), name='attachment_single_parent'),
        ),
        migrations.AddConstraint(
            model_name='attachment',
            constraint=models.UniqueConstraint(fields=('document', 'object_key'), name='uq_attachment_document_object_key'),
        ),
    ]
