# Generated by Django 6.0.7 on 2026-10-08 03:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0021_attachment_document_alter_attachment_issue_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GitPullRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=100)),
                ('pr_number', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('state', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('merged', 'Merged')], max_length=20)),
                ('author_username', models.CharField(blank=True, max_length=255, null=True)),
                ('source_branch', models.CharField(blank=True, max_length=255, null=True)),
                ('target_branch', models.CharField(blank=True, max_length=255, null=True)),
                ('url', models.URLField(max_length=1000)),
                ('opened_at', models.DateTimeField()),
                ('merged_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'git_pull_requests',
            },
        ),
        migrations.CreateModel(
            name='GitIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('github', 'GitHub'), ('gitlab', 'GitLab'), ('bitbucket', 'Bitbucket')], max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('disconnected', 'Disconnected'), ('error', 'Error')], default='active', max_length=20)),
                ('connected_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('connected_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='connected_git_integrations', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='git_integrations', to='projects.project')),
            ],
            options={
                'db_table': 'git_integrations',
            },
        ),
        migrations.CreateModel(
            name='GitProviderInstallation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('github', 'GitHub'), ('gitlab', 'GitLab'), ('bitbucket', 'Bitbucket')], max_length=20)),
                ('external_installation_id', models.CharField(max_length=100)),
                ('account_login', models.CharField(max_length=255)),
                ('account_type', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('integration', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='installation', to='integrations.gitintegration')),
            ],
            options={
                'db_table': 'git_provider_installations',
            },
        ),
        migrations.CreateModel(
            name='GitPullRequestIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linked_at', models.DateTimeField(auto_now_add=True)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='git_pull_request_links', to='projects.issue')),
                ('pull_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issue_links', to='integrations.gitpullrequest')),
            ],
            options={
                'db_table': 'git_pull_request_issues',
            },
        ),
        migrations.CreateModel(
            name='GitRepository',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_repository_id', models.CharField(max_length=100)),
                ('owner', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('full_name', models.CharField(max_length=511)),
                ('repository_url', models.URLField(max_length=1000)),
                ('default_branch', models.CharField(blank=True, max_length=255, null=True)),
                ('visibility', models.CharField(blank=True, choices=[('public', 'Public'), ('private', 'Private')], max_length=20, null=True)),
                ('description', models.TextField(blank=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repositories', to='integrations.gitintegration')),
            ],
            options={
                'db_table': 'git_repositories',
            },
        ),
        migrations.AddField(
            model_name='gitpullrequest',
            name='repository',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pull_requests', to='integrations.gitrepository'),
        ),
        migrations.CreateModel(
            name='GitCommit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sha', models.CharField(max_length=64)),
                ('message', models.TextField()),
                ('author_name', models.CharField(blank=True, max_length=255, null=True)),
                ('author_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('author_username', models.CharField(blank=True, max_length=255, null=True)),
                ('branch', models.CharField(blank=True, max_length=255, null=True)),
                ('url', models.URLField(blank=True, max_length=1000, null=True)),
                ('committed_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commits', to='integrations.gitrepository')),
            ],
            options={
                'db_table': 'git_commits',
            },
        ),
        migrations.CreateModel(
            name='GitWebhookDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=20)),
                ('delivery_id', models.CharField(max_length=255)),
                ('event_type', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('received', 'Received'), ('processing', 'Processing'), ('processed', 'Processed'), ('failed', 'Failed')], default='received', max_length=20)),
                ('payload', models.JSONField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhook_deliveries', to='integrations.gitintegration')),
            ],
            options={
                'db_table': 'git_webhook_deliveries',
            },
        ),
        migrations.CreateModel(
            name='GitCommitIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linked_at', models.DateTimeField(auto_now_add=True)),
                ('commit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issue_links', to='integrations.gitcommit')),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='git_commit_links', to='projects.issue')),
            ],
            options={
                'db_table': 'git_commit_issues',
                'indexes': [models.Index(fields=['commit'], name='idx_git_commit_issues_commit'), models.Index(fields=['issue'], name='idx_git_commit_issues_issue')],
                'constraints': [models.UniqueConstraint(fields=('commit', 'issue'), name='uq_git_commit_issue')],
            },
        ),
        migrations.AddIndex(
            model_name='gitintegration',
            index=models.Index(fields=['project'], name='idx_git_integrations_project'),
        ),
        migrations.AddIndex(
            model_name='gitintegration',
            index=models.Index(fields=['provider'], name='idx_git_integrations_provider'),
        ),
        migrations.AddIndex(
            model_name='gitintegration',
            index=models.Index(fields=['status'], name='idx_git_integrations_status'),
        ),
        migrations.AddConstraint(
            model_name='gitintegration',
            constraint=models.UniqueConstraint(fields=('project', 'provider'), name='uq_git_integration_project_provider'),
        ),
        migrations.AddIndex(
            model_name='gitproviderinstallation',
            index=models.Index(fields=['provider'], name='idx_git_installations_provider'),
        ),
        migrations.AddIndex(
            model_name='gitproviderinstallation',
            index=models.Index(fields=['account_login'], name='idx_git_installations_account'),
        ),
        migrations.AddConstraint(
            model_name='gitproviderinstallation',
            constraint=models.UniqueConstraint(fields=('provider', 'external_installation_id'), name='uq_git_provider_installation_external'),
        ),
        migrations.AddIndex(
            model_name='gitpullrequestissue',
            index=models.Index(fields=['pull_request'], name='idx_git_pr_issues_pr'),
        ),
        migrations.AddIndex(
            model_name='gitpullrequestissue',
            index=models.Index(fields=['issue'], name='idx_git_pr_issues_issue'),
        ),
        migrations.AddConstraint(
            model_name='gitpullrequestissue',
            constraint=models.UniqueConstraint(fields=('pull_request', 'issue'), name='uq_git_pr_issue'),
        ),
        migrations.AddIndex(
            model_name='gitrepository',
            index=models.Index(fields=['integration'], name='idx_git_repositories_integration'),
        ),
        migrations.AddIndex(
            model_name='gitrepository',
            index=models.Index(fields=['full_name'], name='idx_git_repositories_full_name'),
        ),
        migrations.AddConstraint(
            model_name='gitrepository',
            constraint=models.UniqueConstraint(fields=('integration', 'external_repository_id'), name='uq_git_repository_external'),
        ),
        migrations.AddIndex(
            model_name='gitpullrequest',
            index=models.Index(fields=['repository'], name='idx_git_pr_repository'),
        ),
        migrations.AddIndex(
            model_name='gitpullrequest',
            index=models.Index(fields=['state'], name='idx_git_pr_state'),
        ),
        migrations.AddConstraint(
            model_name='gitpullrequest',
            constraint=models.UniqueConstraint(fields=('repository', 'pr_number'), name='uq_git_pr_number'),
        ),
        migrations.AddConstraint(
            model_name='gitpullrequest',
            constraint=models.UniqueConstraint(fields=('repository', 'external_id'), name='uq_git_pr_external'),
        ),
        migrations.AddIndex(
            model_name='gitcommit',
            index=models.Index(fields=['repository'], name='idx_git_commits_repository'),
        ),
        migrations.AddIndex(
            model_name='gitcommit',
            index=models.Index(fields=['committed_at'], name='idx_git_commits_committed_at'),
        ),
        migrations.AddConstraint(
            model_name='gitcommit',
            constraint=models.UniqueConstraint(fields=('repository', 'sha'), name='uq_git_commit_sha'),
        ),
        migrations.AddIndex(
            model_name='gitwebhookdelivery',
            index=models.Index(fields=['integration'], name='idx_git_webhooks_integration'),
        ),
        migrations.AddIndex(
            model_name='gitwebhookdelivery',
            index=models.Index(fields=['event_type'], name='idx_git_webhooks_event'),
        ),
        migrations.AddIndex(
            model_name='gitwebhookdelivery',
            index=models.Index(fields=['status'], name='idx_git_webhooks_status'),
        ),
        migrations.AddIndex(
            model_name='gitwebhookdelivery',
            index=models.Index(fields=['received_at'], name='idx_git_webhooks_received'),
        ),
        migrations.AddConstraint(
            model_name='gitwebhookdelivery',
            constraint=models.UniqueConstraint(fields=('provider', 'delivery_id'), name='uq_git_webhook_delivery'),
        ),
    ]
