# Generated by Django 6.0.7 on 2026-10-08 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='gitproviderinstallation',
            name='uq_git_provider_installation_external',
        ),
        migrations.RenameIndex(
            model_name='gitrepository',
            new_name='idx_git_repo_integration',
            old_name='idx_git_repositories_integration',
        ),
    ]
