# Generated by Django 6.0.7 on 2026-10-08 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0002_remove_gitproviderinstallation_uq_git_provider_installation_external_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gitpullrequest',
            name='draft',
            field=models.BooleanField(default=False),
        ),
    ]
