# Generated by Django 6.0.7 on 2026-10-09 01:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0003_gitpullrequest_draft'),
    ]

    operations = [
        migrations.CreateModel(
            name='GitIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=100)),
                ('issue_number', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('state', models.CharField(max_length=20)),
                ('author_username', models.CharField(blank=True, max_length=255, null=True)),
                ('url', models.URLField(max_length=1000)),
                ('opened_at', models.DateTimeField()),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='integrations.gitrepository')),
            ],
            options={
                'db_table': 'git_issues',
                'indexes': [models.Index(fields=['repository'], name='idx_git_issues_repository'), models.Index(fields=['repository', 'state'], name='idx_git_issues_repository_state')],
                'constraints': [models.UniqueConstraint(fields=('repository', 'issue_number'), name='uq_git_issue_repository_number'), models.UniqueConstraint(fields=('repository', 'external_id'), name='uq_git_issue_repository_external_id')],
            },
        ),
    ]
