# Generated by Django 6.0.7 on 2026-10-09 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0004_gitissue'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='gitissue',
            new_name='idx_git_issues_repo_state',
            old_name='idx_git_issues_repository_state',
        ),
    ]
