# Generated by Django 6.0.7 on 2026-10-09 03:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0005_rename_idx_git_issues_repository_state_idx_git_issues_repo_state'),
        ('projects', '0021_attachment_document_alter_attachment_issue_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GitIssueWorkItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linked_at', models.DateTimeField(auto_now_add=True)),
                ('git_issue', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='work_item_link', to='integrations.gitissue')),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='git_issue_links', to='projects.issue')),
            ],
            options={
                'db_table': 'git_issue_work_items',
                'indexes': [models.Index(fields=['issue'], name='idx_git_issue_work_item')],
            },
        ),
    ]
