from django.urls import path

from .views import (
    OrganizationArchiveView,
    OrganizationBrandingView,
    OrganizationDashboardView,
    OrganizationDeleteConfirmView,
    OrganizationDeleteRequestView,
    OrganizationOptionsView,
    OrganizationPreferenceView,
    OrganizationSettingsView,
    OrganizationView,
)

urlpatterns = [
    path(
        "",
        OrganizationView.as_view(),
        name="organization",
    ),
    path(
        "options/",
        OrganizationOptionsView.as_view(),
        name="organization-options",
    ),
    path(
        "<slug:slug>/dashboard/",
        OrganizationDashboardView.as_view(),
        name="organization-dashboard",
    ),
    path(
        "<slug:slug>/settings/",
        OrganizationSettingsView.as_view(),
        name="organization-settings",
    ),
    path(
        "<slug:slug>/branding/",
        OrganizationBrandingView.as_view(),
        name="organization-branding",
    ),
    path(
        "<slug:slug>/archive/",
        OrganizationArchiveView.as_view(),
        name="organization-archive",
    ),
    path(
        "<slug:slug>/delete/request/",
        OrganizationDeleteRequestView.as_view(),
        name="organization-delete-request",
    ),
    path(
        "<slug:slug>/delete/confirm/",
        OrganizationDeleteConfirmView.as_view(),
        name="organization-delete-confirm",
    ),
    path(
        "<slug:slug>/preferences/",
        OrganizationPreferenceView.as_view(),
        name="organization-preferences",
    ),
]
