from django.urls import path

from .views import (
    KanbanBoardView,
    KanbanColumnIssueView,
    KanbanIssuePositionView,
    KanbanIssueStatusView,
    KanbanSprintFilterView,
    ProjectArchiveStatusView,
    ProjectArchiveView,
    ProjectDeleteView,
    ProjectMemberView,
    ProjectOptionsView,
    ProjectSettingsView,
    ProjectUnarchiveView,
    ProjectView,
    ProjectWorkflowView,
    SprintDetailView,
    SprintStartView,
    SprintView,
    WorkflowStatusPositionView,
    WorkflowStatusView,
    WorkflowTransitionView,
)

urlpatterns = [
    path("", ProjectView.as_view(), name="projects"),
    path("options/", ProjectOptionsView.as_view(), name="project-options"),
    path(
        "<slug:project_slug>/settings/",
        ProjectSettingsView.as_view(),
        name="project-settings",
    ),
    path(
        "<slug:project_slug>/archive/",
        ProjectArchiveView.as_view(),
        name="project-archive",
    ),
    path(
        "<slug:project_slug>/unarchive/",
        ProjectUnarchiveView.as_view(),
        name="project-unarchive",
    ),
    path(
        "<slug:project_slug>/archive-status/",
        ProjectArchiveStatusView.as_view(),
        name="project-archive-status",
    ),
    path(
        "<slug:project_slug>/members/",
        ProjectMemberView.as_view(),
        name="project-members",
    ),
    path(
        "<slug:project_slug>/members/<int:user_id>/",
        ProjectMemberView.as_view(),
        name="project-member",
    ),
    path("<slug:project_slug>/", ProjectDeleteView.as_view(), name="project-delete"),
    path(
        "<slug:project_slug>/workflow/",
        ProjectWorkflowView.as_view(),
        name="project-workflow",
    ),
    path(
        "<slug:project_slug>/workflow/statuses/",
        WorkflowStatusView.as_view(),
        name="workflow-statuses",
    ),
    path(
        "<slug:project_slug>/workflow/statuses/<int:status_id>/",
        WorkflowStatusView.as_view(),
        name="workflow-status-detail",
    ),
    path(
        "<slug:project_slug>/workflow/statuses/<int:status_id>/position/",
        WorkflowStatusPositionView.as_view(),
        name="workflow-status-position",
    ),
    path(
        "<slug:project_slug>/workflow/transitions/",
        WorkflowTransitionView.as_view(),
        name="workflow-transitions",
    ),
    path(
        "<slug:project_slug>/workflow/transitions/<int:transition_id>/",
        WorkflowTransitionView.as_view(),
        name="workflow-transition-detail",
    ),
    path("<slug:project_slug>/sprints/", SprintView.as_view(), name="project-sprints"),
    path(
        "<slug:project_slug>/sprints/<int:sprint_id>/",
        SprintDetailView.as_view(),
        name="sprint-detail",
    ),
    path(
        "<slug:project_slug>/sprints/<int:sprint_id>/start/",
        SprintStartView.as_view(),
        name="sprint-start",
    ),
    path(
        "<slug:project_slug>/board/",
        KanbanBoardView.as_view(),
        name="project-kanban-board",
    ),
    path(
        "<slug:project_slug>/board/sprints/",
        KanbanSprintFilterView.as_view(),
        name="kanban-sprint-filter",
    ),
    path(
        "<slug:project_slug>/board/columns/<int:status_id>/issues/",
        KanbanColumnIssueView.as_view(),
        name="kanban-column-issues",
    ),
    path(
        "<slug:project_slug>/board/issues/<int:issue_id>/status/",
        KanbanIssueStatusView.as_view(),
        name="kanban-issue-status",
    ),
    path(
        "<slug:project_slug>/board/issues/<int:issue_id>/position/",
        KanbanIssuePositionView.as_view(),
        name="kanban-issue-position",
    ),
]
