OTP_REGISTER_PREFIX = "auth:otp:register"
REGISTRATION_DATA_PREFIX = "auth:register:data"
PASSWORD_RESET_PREFIX = "auth:password-reset"
OTP_ACCOUNT_DELETION_PREFIX = "otp:account-deletion"
ACCOUNT_DELETION_CONFIRMATION = "DELETE MY ACCOUNT"
RESEND_COOLDOWN_SECONDS = 60