from django.urls import path
from .views import (
    ConfirmAccountDeletionView,
    CurrentUserView,
    ForgotPasswordView,
    GoogleAuthView,
    LoginView,
    LogoutView,
    RefreshTokenView,
    RequestAccountDeletionView,
    ResetPasswordView,
    SendOTPView,
    RegisterView,
)

urlpatterns = [
    path(
        "send-otp/",
        SendOTPView.as_view(),
        name="send-otp",
    ),
    path(
        "register/",
        RegisterView.as_view(),
        name="register",
    ),
    path(
        "login/",
        LoginView.as_view(),
        name="login",
    ),
    path(
        "refresh/",
        RefreshTokenView.as_view(),
        name="refresh-token",
    ),
    path(
        "logout/",
        LogoutView.as_view(),
        name="logout",
    ),
    path(
        "me/",
        CurrentUserView.as_view(),
        name="current-user",
    ),
    path(
        "google/",
        GoogleAuthView.as_view(),
        name="google-auth",
    ),
    path(
        "forgot-password/",
        ForgotPasswordView.as_view(),
        name="forgot-password",
    ),
    path(
        "reset-password/",
        ResetPasswordView.as_view(),
        name="reset-password",
    ),
    path(
        "delete-account/request/",
        RequestAccountDeletionView.as_view(),
        name="request-account-deletion",
    ),
    path(
        "delete-account/confirm/",
        ConfirmAccountDeletionView.as_view(),
        name="confirm-account-deletion",
    ),
]
