# Generated by Django 6.0.7 on 2026-08-11 12:05

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, max_length=500)),
                ('slug', models.SlugField(max_length=63, unique=True)),
                ('icon', models.CharField(default='hexagon', max_length=100)),
                ('accent_color', models.CharField(default='amber', max_length=20)),
                ('logo_url', models.URLField(blank=True, max_length=500, null=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_organizations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'organizations',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['slug'], name='idx_organization_slug'), models.Index(fields=['deleted_at'], name='idx_organization_deleted_at'), models.Index(fields=['deleted_at', 'is_archived'], name='idx_organization_status')],
            },
        ),
    ]
