# Generated by Django 6.0.7 on 2026-08-18 06:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allow_admin_invitations', models.BooleanField(default=True)),
                ('allow_member_invitations', models.BooleanField(default=False)),
                ('allow_member_project_creation', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to='organizations.organization')),
            ],
        ),
    ]
