# Generated by Django 6.0.7 on 2026-08-19 07:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_seed_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationrole',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organizationrole',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
